/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Phamagest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOYIFANE
 */
public class Medicaments extends javax.swing.JFrame {

    /**
     * Creates new form Medicaments
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet res = null;

    public Medicaments() {
        initComponents();
        con = Connect.getConnection();
        this.setLocationRelativeTo(null);
        incrementid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtID = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtFournisseurs = new javax.swing.JTextField();
        txtQuantite = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMedoc = new javax.swing.JTable();
        dateFab = new com.toedter.calendar.JDateChooser();
        dateExp = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Medicaments");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 880, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, 880, 0));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 210, -1));
        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, -1));
        getContentPane().add(txtFournisseurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));
        getContentPane().add(txtQuantite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 210, -1));
        getContentPane().add(txtPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 210, -1));

        jLabel2.setText("Prix");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setText("Nom");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel5.setText("Fournisseur");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel6.setText("Quantite");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 243, 880, 10));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 20, 20));

        tbMedoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom", "Quantie", "Prix", "Fournisseurs", "Fabrication", "Expiration"
            }
        ));
        tbMedoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMedocMouseClicked(evt);
            }
        });
        tbMedoc.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbMedocComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tbMedoc);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 880, 130));
        getContentPane().add(dateFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 210, -1));
        getContentPane().add(dateExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 210, -1));

        jLabel7.setText("Fabrication");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel8.setText("Expiration");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String fournisseurs = txtFournisseurs.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        Date dateF = dateFab.getDate();
        Date dateE = dateExp.getDate();
        String dateFabrication = "";
        String dateExpiration = "";
        if (dateF != null) {
            dateFabrication = df.format(dateFab.getDate());
        }
        if (dateE != null) {
            dateExpiration = df.format(dateExp.getDate());
        }
        String id = txtID.getText();
        String nom = txtNom.getText();
        int qte = Integer.parseInt(txtQuantite.getText());

        int prix = Integer.parseInt(txtPrix.getText());

        if (nom.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ Nom est vide");
        } else if (fournisseurs.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ Fournisseur est vide");
        } else if (qte == 0) {
            JOptionPane.showMessageDialog(null, "Le champ Quantite est vide");
        } else if (prix == 0) {
            JOptionPane.showMessageDialog(null, "Le champ Prix est vide");
        } else if (dateFabrication.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ date de fabrication est vide");
        } else if (dateExpiration.equals("")) {
            JOptionPane.showMessageDialog(null, "Le champ date d'Expriration est vide");
        } else {
            try {
                con = Connect.getConnection();
                pst = con.prepareStatement("INSERT INTO medicaments (nom,quantite,prix,fournisseurs,fabircation,expiration) values(?,?,?,?,?,?)");
                pst.setString(1, nom);
                pst.setInt(2, qte);
                pst.setInt(3, prix);
                pst.setString(4, fournisseurs);
                pst.setString(5, dateFabrication);
                pst.setString(6, dateExpiration);
                res = pst.executeQuery();
                JOptionPane.showConfirmDialog(null, "Voulez vous continuer?", "Message", JOptionPane.YES_NO_OPTION);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Le médicament a bien été inséré avec succès");
            }
        }
        setVisible(false);
        new Medicaments().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbMedocComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbMedocComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tbMedocComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbMedoc.getModel();
        try {
            con = Connect.getConnection();
            pst = con.prepareStatement("SELECT * FROM medicaments ORDER BY idmed ASC ");
            res = pst.executeQuery();
            while (res.next()) {
                model.addRow(new Object[]{res.getString("idmed"), res.getString("nom"), res.getString("quantite"),
                    res.getString("prix"), res.getString("fournisseurs"),
                    res.getString("fabircation"), res.getString("expiration")});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String nom = txtNom.getText();
        String fournisseur = txtFournisseurs.getText();
        String qte = txtQuantite.getText();
        String prix = txtPrix.getText();
        String dateF = dateFab.getDateFormatString();
        String dateE = dateExp.getDateFormatString();

        if (nom.equals("") || fournisseur.equals("") || qte.equals("") || prix.equals("")
                || dateF.equals("") || dateE.equals("")) {
            JOptionPane.showMessageDialog(null, "Completez les informations", "Information manquante", 2);
        } else {
            String sql = " UPDATE medicaments set nom='" + nom + "',quantite='" + qte + "',prix='" + prix + "',fournisseurs='" + fournisseur + "',fabircation='" + dateF + "',expiration='" + dateE + "' where idmed='" + id + "' ";
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Modification reusi !", "Message", 1);
                setVisible(false);
                new Medicaments().setVisible(true);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tbMedocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMedocMouseClicked
        // TODO add your handling code here:
        int row = tbMedoc.getSelectedRow();
        String t = tbMedoc.getModel().getValueAt(row, 0).toString();
        String sql = "select * from medicaments where idmed='" + t + "' ";
        try {
            pst = con.prepareStatement(sql);
            res = pst.executeQuery();
            if (res.next()) {
                String id = res.getString("idmed");
                txtID.setText(id);
                String nom = res.getString("nom");
                txtNom.setText(nom);
                String quantite = res.getString("quantite");
                txtQuantite.setText(quantite);
                String prix = res.getString("prix");
                txtPrix.setText(prix);
                String fournisseur = res.getString("fournisseurs");
                txtFournisseurs.setText(fournisseur);
                String dateF = res.getString("fabircation");
                dateFab.setDateFormatString(dateF);
                String dateE = res.getString("expiration");
                dateExp.setDateFormatString(dateE);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bonnes informations", "Erreur", 2);

        }
    }//GEN-LAST:event_tbMedocMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (txtID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Entrez l'ID que vous souhaitez supprimer", "Information manquante", 2);
        } else if (verifierm()) {
            String sql = "DELETE FROM medicaments where idmed='" + txtID.getText() + "' ";
            try {
                int check = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de supprimer ce medicament", "Message", JOptionPane.YES_NO_OPTION);
                if (check == 0) {
                    pst = con.prepareStatement(sql);
                    pst.executeQuery();
                    JOptionPane.showMessageDialog(null, "Medicament supprimé avec succès", "Message", 1);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Medicament supprimé avec succès", "Message", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "L'utilisateur est introuvable", "Mauvaise opération", 2);
        }
        setVisible(false);
        new Medicaments().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicaments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicaments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicaments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicaments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicaments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateExp;
    private com.toedter.calendar.JDateChooser dateFab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tbMedoc;
    private javax.swing.JTextField txtFournisseurs;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtQuantite;
    // End of variables declaration//GEN-END:variables

    private boolean verifierm() {
        boolean verifier = false;
        String sql = "select idmed from medicaments where idmed='" + txtID.getText() + "' ";
        try {
            pst = con.prepareStatement(sql);
            res = pst.executeQuery();
            if (res.next()) {
                verifier = true;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", 2);
        }
        return verifier;

    }

    public void incrementid() {
        try {
            String sql = "SELECT idmed FROM medicaments order by idmed desc limit 1";
            pst = con.prepareStatement(sql);
            res = pst.executeQuery();
            if (res.next()) {
                int id = res.getInt(1);
                int n = id + 1;
                txtID.setText(Integer.toString(n));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", 2);
        }
    }

}
